sudo: required
env:
  global:
    - MINIO_VER="RELEASE.2019-09-26T19-42-35Z"
    - ALPINE_VER="3.10"
    - COMPOSE_HTTP_TIMEOUT="300"
    - UID="2000"
    - GID="2000"
    - COVERALLS_SERVICE_NAME="travis-ci"
    - COVERALLS_REPO_TOKEN="fd0BoXG46TPReEem0uMy7BJO5j0w1MQiY"
services: 
- docker
main: &main
      stage: "Tests & Coverage: Alpine"
      os: linux
      dist: xenial # precise, trusty, xenial, bionic
      language: shell
      script:
        - docker-compose -f LNX-docker-compose.yml up --build --exit-code-from app
jobs:
  include:
    - stage: "Lint: Syntax"
      language: python
      install:
        - pip install flake8
      script:
        - flake8 datajoint --count --select=E9,F63,F7,F82 --show-source --statistics
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.7"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.6"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.5"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.6"
    - stage: "Lint: Style"
      language: python
      install:
        - pip install flake8
      script:
        - |
          flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E722,F401,W605 datajoint \
          --count --max-complexity=62 --max-line-length=127 --statistics